# Infra deployment engine
workspace: "" # Working directory for testrunner
ssh_key_option: "id_shared" # "id_shared" or "id_rsa" for your local public key
username: ""  # Fill your username
nodeuser: "sles"  # Default node username
mirrors: "ibs-mirror.prv.suse.net" # mirrors for downloading packages

# Skuba setup
skuba:
  binpath: "" # path to skuba binary
  srcpath: "" # path to skuba source

# platform settings
terraform:
  tfdir: ""  # path to terraform templates
  tfvars: "" # terraform vars

openstack:
  openrc: "" #os.getenv("OPENRC")

vmware:
  env_file: "" #os.getenv("ENV_FILE")
  template_name: "SLES15-SP1-GM-guestinfo" #os.getenv("TEMPLATE_NAME")

# node settings
lb:
  count: 1
  memory: 8192
  cpu: 4

master:
  count: 3
  memory: 4096
  cpu: 4

worker:
  count: 3
  memory: 4096
  cpu: 2
